name: Multipy runtime nightly release + tests

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

  pull_request:

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.8]
        platform: [linux.2xlarge, linux.4xlarge]
        abi: [0,1]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Build multipy
        uses: pytorch/multipy/.github/workflows/build_multipy.yml@51df5ec924977c50d2b0218cff845fe9cec93a4e
        with:
          abi_version: ${{ matrix.abi }}
          python-version: ${{ matrix.python-version }}
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests with ABI=${{ matrix.abi }}
        if: ${{ matrix.abi }} == 1
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
              cd multipy/runtime/build
              ./test_deploy

      - name: create tarball [click me to get a list of files for the nightly release]
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
              cd multipy/runtime/build/dist
              tar -czvf multipy_runtime.tar.gz runtime/

      - name: Update nightly release
        if: ${{ matrix.abi }} == 0
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly-runtime
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            multipy/runtime/build/dist/multipy_runtime.tar.gz

      - name: Update nightly release
        if: ${{ matrix.abi }} == 1
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly-runtime-with-abi-one
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            multipy/runtime/build/dist/multipy_runtime.tar.gz
