name: Multipy runtime nightly release + tests with ABI 0

on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.8]
        platform: [linux.2xlarge]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Build multipy
        uses: pytorch/multipy/.github/workflows/build_multipy.yml
        with:
          abi_0: true
          python-version: ${{ matrix.python-version }}
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test_deploy
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
              cd multipy/runtime
              cd build
              conda run -n multipy_runtime_env cmake --install . --prefix "."
              ./test_deploy

      - name: create tarball [click me to get a list of files for the nightly release]
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
              cd multipy/runtime/build/dist
              tar -czvf multipy_runtime.tar.gz runtime/

      - name: Update nightly release
        uses: pyTooling/Actions/releaser@main
        with:
          tag: nightly-runtime
          rm: true
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            multipy/runtime/build/dist/multipy_runtime.tar.gz
