name: Multipy runtime Unit test with ABI 1

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unittest:
    strategy:
      matrix:
        python-version: [3.8]
        platform: [linux.2xlarge]
      fail-fast: false
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Build multipy with ABI=1
        uses: pytorch/multipy/.github/workflows/build_multipy.yml@51df5ec924977c50d2b0218cff845fe9cec93a4e
        with:
          abi_0: false
          python-version: ${{ matrix.python-version }}
        secrets:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: test_deploy
        shell: bash -l {0}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
              cd multipy/runtime
              cd build
              conda run -n multipy_runtime_env cmake --install . --prefix "."
              ./test_deploy
